### ISSUE TITLE
prep_word2vec requires R >= 3.2.0

### ISSUE THREAD

**Issue by muranava** [bmschmidt/wordVectors#1]
## hi am getting this error when trying to parse the text:

Beginning tokenization to text file at cookbooks.txt
Error in prep_word2vec("cookbooks", "cookbooks.txt", lowercase = T) :

**Comment by bmschmidt** [comment]
`dir.exists` was added as of R 3.2.0. (I didn't know it was this new, and wouldn't have used it if I did.)

You can fix this by updating to the latest version of R.

I should put a dependency tag on the package until I can fix it to something more general.

**Comment by muranava** [comment]
great thanks updating R works

**Comment by bmschmidt** [comment]
Thanks for the note. Just re-opening as a reminder for the dependency tag.

**Comment by bmschmidt** [comment]
Fixed in v1.2 (though not tested in R < 3.20)
