### ISSUE TITLE
Cache magnitudes to improve repeated cosine similarity queries performance

### ISSUE THREAD

**Issue by mateuszr** [bmschmidt/wordVectors#12]
After reading binary file of 320895 rows and 100 columns, it takes around 15-20 seconds to get  result of "nearest_to" call. Is this normal behaviour or rather some quirk? The gensim word2vec implementation is rather quick on the exactly same model (it takes less than 1s to get similar vectors).

The code is the following:
model <- read.vectors("model.bin")
nearest_to(model,model[["word"]])

**Comment by bmschmidt** [comment]
Hmm, that's a bit worse than it should be unless you're on a very old computer. There are several reasons the C code should be a few times faster, but more than 20x is too much. With a 320,000 x 100 matrix, on my laptop (2013 macbook air) it takes about 2.3 seconds to do a nearest_to call. It's possible you're running out of RAM and switching to swap (the R function takes more memory than the C one), or that you have a [BLAS library poorly tuned to your architecture](http://www.r-bloggers.com/for-faster-r-use-openblas-instead-better-than-atlas-trivial-to-switch-to-on-ubuntu/). (The latter is pretty unlikely.)

There are a few optimizations that would speed this up. I just pushed one set that should marginally increase the speed of these queries (by maybe 10% or so).

### For later (soon?)

There's another much bigger performance improvement that I haven't done that I want to flag for later. When you do multiple similarities on a single matrix, the most expensive calculation is the magnitudes of every row in the original matrix. This could be cached for subsequent queries; possibly by adding a 'magnitudes' slot to the VSM object.

The first cosine similarity query (or nearest neighbor query, or anything else that builds on cosine similarity) would still take a second or two; but later ones might be much faster.

I suspect that word2vec's C code does something like this. There might be a little overhead (it would increase the size of a 100-dimensional vector model by 1%, at least), but cosine similarity is a fundamental enough operation for this package that it's probably worth it.

**Comment by bmschmidt** [comment]
Caching is now implemented as of v 1.3

I also noticed some unnecessary duplication of matrices happening internally, which is also gone.
