### ISSUE TITLE
error in scan

### ISSUE THREAD

**Issue by shawngraham** [bmschmidt/wordVectors#14]
Hi Ben,

I accidentally reinstalled wordVectors, and now, on a file that worked fine before, I get this kind of error:

```Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  scan() expected 'a real', got 'm��9&x�9�����&e���8x0S9���8�_l7m�{�*9DD��ܲ�86R��҅�c�g�ƒ�0O49�|S9P�O9�V�8���8y鄹G(�����9/݄9�X9��(�z[�9!i'

In addition: Warning messages:

1: In utils::read.table(filename, header = F, skip = 1, colClasses = c("character",  :
  line 4 appears to contain embedded nulls

2: In utils::read.table(filename, header = F, skip = 1, colClasses = c("character",  :
  line 5 appears to contain embedded nulls```

...so I was thinking that maybe it was an encoding issue, but file is in UTF-8, all seems tickety-boo. Wondered what you thought.

**Comment by shawngraham** [comment]
hmm. Never mind! whatever I was doing, I apparently have now sorted it out. Man, so much of what I do is just cargo-cult DH...

**Comment by bmschmidt** [comment]
FTR, this is probably related to my having shifted the default storage format from text to binary to save space and time. If you encounter it again, you might need to explicitly say "binary=TRUE" or "binary=FALSE" in a call to 'read.vectors.'

**Comment by shawngraham** [comment]
ah! cool, thanks!
