### ISSUE TITLE
Error on loading large model

### ISSUE THREAD

**Issue by joehoover** [bmschmidt/wordVectors#24]
I am trying to load the standard google news model, but I received this error: 

`Error in validObject(.Object) : 
  invalid class “VectorSpaceModel” object: Error : cannot allocate vector of size 6.7 Gb`

I tried on my macbook and my linux workstation, neither worked. I have no trouble loading this model in gensim. 

Also, these are my R stats: 

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by bmschmidt** [comment]
R is a lot more wasteful of memory than numpy/gensim; it will take at least twice as much RAM to load the same model. (Reason: there's no provision for single-precision floats in R the way there is in numpy, so the model takes twice as many bytes to store the same information as doubles; and there's a tendency in R to unnecessarily copy objects that I haven't totally snuffed out.)

If you want to look at a smaller version of the data, try passing in the `nrow` parameter. `read.vectors("googlenews.bin",nrow=1e06)` will load in the 1 million most common words.

You can also load only selected columns by passing an arg to `cols` (eg, cols=1:100 to load only the first 100 of 300 dimensions in Google News); but I'm not sure if that's entirely kosher, and haven't inspected the results closely.

**Comment by joehoover** [comment]
Ah, stupid R. I'm running 64bit on my linux station and I have 24g ram, so
I think this is an R issue and not a system issue, since the raw vectors
are only about 3g. Do you know if I can increase the memory ceiling for R
or something like that?

I just need to extract the word vectors for 50 words, so it's certainly a
bit silly to load the entire model. I don't suppose your package supports
loading specific rows, does it? I can of course just extract the vectors
using gensim, but this is for a paper and all of the other analyses will be
conducted in R, so I'd rather do everything in R if possible.

Thanks for your help!

Best,
Joe

On Tue, Jan 10, 2017 at 1:02 PM, Benjamin Schmidt <notifications@github.com>
wrote:

> R is a lot more wasteful of memory than numpy/gensim; it will take at
> least twice as much RAM to load the same model. (Reason: there's no
> provision for single-precision floats in R the way there is in numpy, so
> the model takes twice as many bytes to store the same information as
> doubles; and there's a tendency in R to unnecessarily copy objects that I
> haven't totally snuffed out.)
>
> If you want to look at a smaller version of the data, try passing in the
> nrow parameter. read.vectors("googlenews.bin",nrow=1e06) will load in the
> 1 million most common words.
>
> You can also load only selected columns by passing an arg to cols (eg,
> cols=1:100 to load only the first 100 of 300 dimensions in Google News);
> but I'm not sure if that's entirely kosher, and haven't inspected the
> results closely.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bmschmidt_wordVectors_issues_24-23issuecomment-2D271696892&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=wmdJURb7N7zJAoIxqew9sw&m=3Vng6CuZRZSHBWXoTyTnF_IRWcxSqifL831JtRW0vZg&s=sHgvCuHuvWWGFz5C2bS-kJ0tM8NgT29uOAjwzqV-X7o&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKwVZtZpXNoln8KDc77WgWsXYpPG1-5FYXks5rQ-5FHSgaJpZM4Lf2za&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=wmdJURb7N7zJAoIxqew9sw&m=3Vng6CuZRZSHBWXoTyTnF_IRWcxSqifL831JtRW0vZg&s=CJQw0drh2ATReCesrwOpTCXWupLxPOmln-GzH5jgrhA&e=>
> .
>



-- 
Joe Hoover
Doctoral Student & Dornsife Fellow
Department of Psychology
University of Southern California
Office: SGM 604
Email: jehoover@usc.edu

**Comment by bmschmidt** [comment]
Huh, that's odd. Pretty sure that I loaded to full Google News on one of my big workstations at some point, but I might be hallucinating that.

I did expand read.vectors at some point to allow you to read in just a word list. Looks like I never pushed that commit, though, and it's currently tangled up in a lot of experimental stuff… let me much around with git branches for a minute and maybe I can return it here.

**Comment by bmschmidt** [comment]
OK, I found that missing code and merged it into the main branch here. (I'm surprised it would be useful for anyone else!): You can just pass a rowname_list argument to read.binary.vectors or read.vectors like so. (Or a `rowname_regexp`, for that matter.) It will churn through the whole thing, but only map into memory the words in your list.)


For example:

```
> foo = read.binary.vectors("~/word2vec_models/short_google_news.bin", rowname_list = c("good","bad","ugly"))
Reading a word2vec binary file of 100000 rows and 300 columns
  |=========================================================================================================================| 100%
> foo
A VectorSpaceModel object of  3  words and  300  vectors
           [,1]      [,2]        [,3]       [,4]       [,5]        [,6]
good 0.04052734 0.0625000 -0.01745605 0.07861328 0.03271484 -0.01263428
bad  0.06298828 0.1245117  0.11328125 0.07324219 0.03881836  0.07910156
ugly 0.04687500 0.1166992  0.04760742 0.01306152 0.02014160  0.10888672
attr(,".cache")
<environment: 0x32337c378>
```

**Comment by joehoover** [comment]
Ah man, that's awesome! Thanks!

On Tue, Jan 10, 2017 at 2:52 PM, Benjamin Schmidt <notifications@github.com>
wrote:

> OK, I found that missing code and merged it into the main branch here.
> (I'm surprised it would be useful for anyone else!): You can just pass a
> rowname_list argument to read.binary.vectors or read.vectors like so. (Or a
> rowname_regexp, for that matter.) It will churn through the whole thing,
> but only map into memory the words in your list.)
>
> For example:
>
> > foo = read.binary.vectors("~/word2vec_models/short_google_news.bin", rowname_list = c("good","bad","ugly"))
> Reading a word2vec binary file of 100000 rows and 300 columns
>   |=========================================================================================================================| 100%
> > foo
> A VectorSpaceModel object of  3  words and  300  vectors
>            [,1]      [,2]        [,3]       [,4]       [,5]        [,6]
> good 0.04052734 0.0625000 -0.01745605 0.07861328 0.03271484 -0.01263428
> bad  0.06298828 0.1245117  0.11328125 0.07324219 0.03881836  0.07910156
> ugly 0.04687500 0.1166992  0.04760742 0.01306152 0.02014160  0.10888672
> attr(,".cache")
> <environment: 0x32337c378>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bmschmidt_wordVectors_issues_24-23issuecomment-2D271723848&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=wmdJURb7N7zJAoIxqew9sw&m=e26hyL7T_0jN4dbG3b8eRT4kqQYzXRfXZKuNq2zLRTM&s=BI_pG0xdjKxipMumZksRliS1FVJQmsTQ61KVPm9fSKk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKwVZocQJ-5F8k7cb0maFK4Tk77mM0CHQQks5rRAuTgaJpZM4Lf2za&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=wmdJURb7N7zJAoIxqew9sw&m=e26hyL7T_0jN4dbG3b8eRT4kqQYzXRfXZKuNq2zLRTM&s=PprI4nTuehhZHM7k6J6TzvREqcNSLVTrhY2CMBpaKC0&e=>
> .
>



-- 
Joe Hoover
Doctoral Student & Dornsife Fellow
Department of Psychology
University of Southern California
Office: SGM 604
Email: jehoover@usc.edu
