### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by shawngraham** [bmschmidt/wordVectors#3]
Hi Ben,

I'm playing with wordvectors again, trying to replicate your genderless post on Melodee Beals' colonial newspaper database. Everything else is working fine, but when I do this:

``` R
genderless_cnd = cnd %>% reject(cnd[["he"]] - cnd[["she"]]) %>% reject(cnd[["man"]] - cnd[["woman"]])
#gendered CND:
cnd %>% nearest_to(cnd[["she"]],20) %>% names
#genderless CND:
genderless_cnd %>% nearest_to(genderless_cnd[["she"]],20) %>% names
```

I get the error:

``` R
Error in genderless_cnd[["she"]] : subscript out of bounds
```

I've tried paging through the bug tracking by `options(error=recover)` but I'm afraid it's beyond me. Wondered what you thought - have I messed something up?

**Comment by bmschmidt** [comment]
My bad; I patched the code for this post (to force vector projection to inherit the new class attributes) but forgot to push the changes. [They're up now](https://github.com/bmschmidt/wordVectors/commit/4d82b89e80429e03d72d49776071e36107a5e1dc), so you just need to update to the latest version.
