### ISSUE TITLE
Error when using reject()

### ISSUE THREAD

**Issue by danielcarter** [bmschmidt/wordVectors#4]
I'm experimenting with the kind of vector rejection described here: http://bookworm.benschmidt.org/posts/2015-10-30-rejecting-the-gender-binary.html

After creating my model: 

ff_vectors = train_word2vec("data/processed_tweets.txt") 

I try:

beast = ff_vectors[["beast"]] %>% reject(ff_vectors[["points"]])

and get: 

```
Error in crossprod(t(matrix %*% b)/as.vector((b %*% b)), b) : 
  non-conformable arguments
```

Any help would be appreciated. I'm very interested in working more with the package.

**Comment by bmschmidt** [comment]
Hmm. What are the values of `ff_vectors[["beast"]]` and `ff_vectors[["points"]]` on their own? For the record, it should something like this.

```
> chronam_vectors[["beast"]] %>% reject(chronam_vectors[["point"]])
A VectorSpaceModel object of  1  words and  500  vectors
         V1          V2          V3          V4          V5          V6 
-0.22624674 -0.03241363  0.15082521 -0.03974202  0.12423422 -0.07666441 
> chronam_vectors[["beast"]]
A VectorSpaceModel object of  1  words and  500  vectors
       V1        V2        V3        V4        V5        V6 
-0.228465 -0.025260  0.164710 -0.036163  0.125053 -0.078557 
> chronam_vectors[["point"]]
A VectorSpaceModel object of  1  words and  500  vectors
       V1        V2        V3        V4        V5        V6 
-0.057931  0.186821  0.362609  0.093468  0.021383 -0.049426 
```

**Comment by danielcarter** [comment]
I think the values are as they should be:

> ff_vectors[["beast"]]
> A VectorSpaceModel object of  1  words and  100  vectors
>        V1        V2        V3        V4        V5        V6 
> -0.144091  0.161415  0.084825 -0.016912 -0.022438  0.003238 
> 
> ff_vectors[["points"]]
> A VectorSpaceModel object of  1  words and  100  vectors
>        V1        V2        V3        V4        V5        V6 
> -0.280055  0.113142  0.099745  0.131716 -0.079463  0.074753 

Is there any other information that might be helpful? I'm using R version 3.1.0 and RStudio version 0.98.994.

**Comment by bmschmidt** [comment]
Hmm, I'm almost stumped. 

What happens if you just try implementing the code manually?

``` r
matrix = ff_vectors[["beast"]]
vector = ff_vectors[["points"]]

b = as.vector(vector)

projected = crossprod(t(matrix %*% b)/as.vector(b %*% b) , b)

projected
```

Some random questions: 

Have you recloned the repo from github recently? 

What's the OS? (Unlikely to matter)

What's the output of `traceback()` immediately after the error?

**Comment by danielcarter** [comment]
I installed R v 3.2.2, and it works now. Thanks for taking the time to look
into it.

**Comment by bmschmidt** [comment]
Weird. Maybe something to do with updates to other packages that came along? In any case, glad it works.
