### ISSUE TITLE
Vocabulary size is much smaller than it ought to be

### ISSUE THREAD

**Issue by KevinBretonnelCohen** [bmschmidt/wordVectors#7]
"Vocab size" is way off.  See the attached screen shot: 1.4 billion words of PubMedCentral author manuscripts, and the vocabulary size is 1,307, according to the status message output.  Doesn't seem likely.

I'm using whatever version of wordVectors was on GitHub as of mid-January 2015.  Not sure what version of RStudio--I think those 1.4 billion words of text have choked my laptop to death...  OS X.  

![screenshot 2016-01-19 19 48 53](https://cloud.githubusercontent.com/assets/2276123/12436719/d162bf80-bee5-11e5-9c88-974f81d4c90a.png)

**Comment by KevinBretonnelCohen** [comment]
An additional data point regarding the small vocabulary size that's showing up on the status message: I'm trying to run train_word2vec() on a data set that's about 1/10 the size of the data set that I was using yesterday, and it's showing the same vocabulary size--see the attached screen shot...

![screenshot 2016-01-20 12 54 27](https://cloud.githubusercontent.com/assets/2276123/12457932/3bf4aeb4-bf75-11e5-8677-ad3558852382.png)

**Comment by KevinBretonnelCohen** [comment]
Cut the data set down by another order of magnitude--same vocabulary size showing.  See screen shot.

![screenshot 2016-01-20 13 03 19](https://cloud.githubusercontent.com/assets/2276123/12458131/498ede5e-bf76-11e5-879f-1371524f7f60.png)

**Comment by bmschmidt** [comment]
Huh. How are you normalizing the text? I can untar a few pubmed abstracts and run `cat */*.txt | perl -pe 's/[^A-Za-z \n]/ /g;' > all.txt` to get something that gives 40,195 vocab in 5.8 million words.
1. What's the output of `system("head -20 YOURFILENAME | cut -c 1-80")`? Does it look like real text? Or another check is; what are the first twenty `rownames()` of the trained object model?
2. Try rerunning `install_github("bmschmidt/wordVectors")`; maybe the update last week fixed it.
